
obj-$(CONFIG_BCACHE)	+= bcache.o

bcache-y		:= alloc.o\
	bkey.o\
	bkey_methods.o\
	blockdev.o\
	bset.o\
	btree.o\
	buckets.o\
	chardev.o\
	debug.o\
	dirent.o\
	extents.o\
	fs.o\
	gc.o\
	inode.o\
	io.o\
	ioctl.o\
	journal.o\
	keybuf.o\
	keylist.o\
	move.o\
	movinggc.o\
	request.o\
	six.o\
	six_trace.o\
	stats.o\
	super.o\
	sysfs.o\
	tier.o\
	trace.o\
	util.o\
	writeback.o\
	xattr.o

ccflags-y		:= -Werror
